export const keyList = [
  { selector: "#fa-award", icon: "fas fa-award", description: "Le mieux noté" },
  { selector: "#fa-medal", icon: "fas fa-medal", description: "Le plus populaire" },
  { selector: "#fa-heart", icon: "fas fa-heart", description: "Notre coup de coeur" },
  { selector: "#fa-umbrella-beach", icon: "fas fa-umbrella-beach", description: "La meilleure terrasse" },
  { selector: "#fa-instagram", icon: "fab fa-instagram", description: "Le plus instagrammable" },
  { selector: "#fa-crown", icon: "fas fa-crown", description: "Le plus chic" },
  { selector: "#fa-bacon", icon: "fas fa-bacon", description: "Le meilleur brunch" },
  { selector: "#fa-pizza-slice", icon: "fas fa-pizza-slice", description: "La meilleure pizza" },
  { selector: "#fa-carrot", icon: "fas fa-carrot", description: "Le meilleur vegan" },
  { selector: "#fa-hamburger", icon: "fas fa-hamburger", description: "Le meilleur burger" },
  { selector: "#fa-pepper-hot", icon: "fas fa-pepper-hot", description: "Le meilleur méxicain" },
  { selector: "#fa-birthday-cake", icon: "fas fa-birthday-cake", description: "La meilleure pâtisserie" },
  { selector: "#fa-book", icon: "fas fa-book", description: "Pour bouquiner ou travailler" },
  { selector: "#fa-chess", icon: "fas fa-chess", description: "Jeux de société" },
  { selector: "#fa-leaf", icon: "fas fa-leaf", description: "Le meilleur poké" },
  { selector: "#fa-hotdog", icon: "fas fa-hotdog", description: "Le meilleur de l'Allemagne" },
  { selector: "#fa-frog", icon: "fas fa-frog", description: "La meilleure cuisine française" },
  { selector: "#fa-fish", icon: "fas fa-fish", description: "Le meilleur poisson" },
  { selector: "#fa-utensils", icon: "fas fa-utensils", description: "Le meilleur italien" },
  { selector: "#fa-sun", icon: "fas fa-sun", description: "Le meilleur brésilien" },
  { selector: "#fa-torii-gate", icon: "fas fas fa-torii-gate", description: "Le meilleur japonais" },
  { selector: "#fa-mug-hot", icon: "fas fas fa-mug-hot", description: "Le meilleur torréfacteur" },
];
